name: timeline_flutter
description: It is a simple-to-use timeline where you can easily adjust your dimensions, lines, and features according to your content.
version: 1.0.1
homepage: https://github.com/aydemiromer/timeline_flutter

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

